namespace Weapons {
    public enum WeaponAttribute {
		NONE,
		DOUBLE_ATK,
		DOUBLE_ATK_CHANCE,
		ATK_ADD_2_AFTR_USE_GUN,
		STUN_ENEMY_CHANCE,
		PARALISE_ENEMY_CHANCE,
		WEAPON_RANGE_REDUCTION,
	}
}
